name: ci 

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build:
    name: Verify
    uses: amsa-code/.github/.github/workflows/ci.yml@master
    with:
      verify-goal: 'verify javadoc:javadoc site'
